variable "task_envs" {
}

variable "db_private_ips" {
  type        = string
  default     = "10.0.1.238"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair1"
  description = "Key-pair generated by Terraform"
}

variable "pub_ip" {
  description = "Name of the stack."
  default     = "aws_eip.bastion_eip.public_ip"
}


variable "alb_target_group" {
  description = "Name of the stack."
  default     = "aws_alb_target_group.trgp.id"
}



variable "alb_listener" {
  description = "Name of the stack."
  default     = "[aws_alb_listener.alb-listener,]"
}




variable "stack" {
  description = "Name of the stack."
  default     = "tsv_project"
}


variable "family" {
  description = "Family of the Task Definition"
  default     = "petclinic"
}


variable "fargate_cpu" {
  description = "Fargate instance CPU units to provision"
  default     = "512"
}

variable "fargate_memory" {
  description = "Fargate instance memory to provision (in MiB)"
  default     = "1024"
}


variable "fargate-task-service-role" {
  description = "Name of the stack."
  default     = "sersice-role"
}


variable "aws_region" {
  description = "The AWS region to create things in."
  default     = "eu-central-1"
}


variable "cw_log_stream" {
  description = "CloudWatch Log Stream"
  default     = "fargate"
}


variable "container_port" {
  description = "Port exposed by the docker image to redirect traffic to"
  default     = 8080
}

variable "host_port" {
  description = "Port exposed by the docker image to redirect traffic to"
  default     = 8080
}



variable "task_count" {
  description = "Number of ECS tasks to run"
  default     = 1
}


variable "vpc_cidr" {
  description = "CIDR for the VPC"
  default     = "172.17.0.0/16"
}


variable "az_count" {
  description = "Number of AZs to cover in a given AWS region"
  default     = "2"
}